### ISSUE TITLE
VideoList sample videos 404

### ISSUE THREAD

**Issue by acinader** [rokudev/samples#13]
videolist example [fetches the list](https://github.com/rokudev/samples/blob/70ac85d5bcd91b15f4c9dfc5ab48c3e294000996/media/VideoListExample/components/videolistscene.xml#L23) from: http://www.sdktestinglab.com/Tutorial/content/videocontent.xml 

the videos 404 so the sample doesn't work :(

**Comment by acinader** [comment]
Hi @jduval23, why did you close?

Is the sample not supposed to work?  The readme says:

"Often the best way to learn a framework is seeing a working application running. "

The sample doesn't work for me.  I started to look into it and I found that I was unable to get the video URLs.  I have pasted a curl example of what happens below:

```
curl -v http://roku.cpl.delvenetworks.com/media/59021fabe3b645968e382ac726cd6c7b/f8de8daf2ba34aeb90edc55b2d380c3f/b228eeaba0f248c48e01e158f99cd96e/rr_123_segment_1_072715.mp4
*   Trying 208.111.135.94...
* TCP_NODELAY set
* Connected to roku.cpl.delvenetworks.com (208.111.135.94) port 80 (#0)
> GET /media/59021fabe3b645968e382ac726cd6c7b/f8de8daf2ba34aeb90edc55b2d380c3f/b228eeaba0f248c48e01e158f99cd96e/rr_123_segment_1_072715.mp4 HTTP/1.1
> Host: roku.cpl.delvenetworks.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Thu, 25 Jul 2019 17:21:48 GMT
< Content-Type: text/plain; charset=utf-8
< X-Agile-Request-Id: ababa7f00e13f3259f59a668a46bb67b, 7fb63ead67b32a1de3023f8901d01059, 3a0121e36155444c810efcbc3bd96d0c
< Server: CloudStorage
< Content-Length: 0
< Connection: keep-alive
< Access-Control-Allow-Origin: *
<
```

**Comment by jduval23** [comment]
Yep...we're working on changing the feed or the parsing logic. Re-opening.

**Comment by jduval23** [comment]
We've updated the videos in the feed used by this example, and verified that the example is working again.

**Comment by bjimenezned** [comment]
video URLs of that list do not work

**Comment by jduval23** [comment]
Hi,  

I just re-tested the sample, and all five videos in the videolistscene.xml.file work:

 <Content>
<item title="Bip and Bop" description="Apple test stream" hdposterurl="http://logok.org/wp-content/uploads/2014/04/Apple-Logo-black.png" streamformat="hls" url="http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8"/>
<item title="Sintel the Movie" description="a short 15-minute fantasy film " hdposterurl="https://durian.blender.org/wp-content/uploads/2010/04/Sintel1.png" streamformat="mp4" url="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4"/>
<item title="The Biker" description="biker rides along the coast" hdposterurl="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Bicycle_with_Rider.svg/1182px-Bicycle_with_Rider.svg.png" streamformat="hls" url="https://content.jwplatform.com/manifests/yp34SRmf.m3u8"/>
<item title="Parkour in Santorini, Greece" description="Hardcore Parkour!" hdposterurl="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Running_icon_-_Noun_Project_22889.svg/1024px-Running_icon_-_Noun_Project_22889.svg.png" streamformat="hls" url="https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"/>
<item title="MusicDoc" description="Four dudes talk about music" hdposterurl="https://cdn0.iconfinder.com/data/icons/rock-and-roll/512/rock-music-culture_2_copy_2-512.png" streamformat="hls" url="https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8"/>
</Content>

**Comment by raykanani** [comment]
I might be missing something. The video list example doesn't appear to include the file for the list of videos.

When I side load the example, I get the TV template and purple background but not content.

**Comment by jduval23** [comment]
Hi @raykanani,

Can you try again now?

We just added SetCertificatesFile() function so roUrlTransfer() function can handle an HTTPS content feed.

Thanks,

JD
